-- Catalogo de produtos Blackouts

begin;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nome text,
  slug text,
  categoria text default 'outros',
  descricao text,
  banner_url text,
  preco numeric(12,2) default 0,
  preco_promocional numeric(12,2),
  quantidade integer default 0,
  ativo boolean default true,
  destaque boolean default false,
  total_vendas integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.products
  add column if not exists nome text,
  add column if not exists slug text,
  add column if not exists categoria text default 'outros',
  add column if not exists descricao text,
  add column if not exists banner_url text,
  add column if not exists preco numeric(12,2) default 0,
  add column if not exists preco_promocional numeric(12,2),
  add column if not exists quantidade integer default 0,
  add column if not exists ativo boolean default true,
  add column if not exists destaque boolean default false,
  add column if not exists total_vendas integer default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

-- Backfill de colunas legadas, se existirem
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'name'
  ) THEN
    EXECUTE 'update public.products set nome = coalesce(nome, name) where nome is null';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'description'
  ) THEN
    EXECUTE 'update public.products set descricao = coalesce(descricao, description) where descricao is null';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'image_url'
  ) THEN
    EXECUTE 'update public.products set banner_url = coalesce(banner_url, image_url) where banner_url is null';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'price'
  ) THEN
    EXECUTE 'update public.products set preco = coalesce(preco, price) where preco is null';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'quantity'
  ) THEN
    EXECUTE 'update public.products set quantidade = coalesce(quantidade, quantity) where quantidade is null';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'type'
  ) THEN
    EXECUTE 'update public.products set categoria = coalesce(categoria, type) where categoria is null';
  END IF;
END $$;

-- Normalizacao de categoria
update public.products
  set categoria = lower(categoria)
  where categoria is not null;

update public.products set categoria = 'steam keys'
  where categoria in ('steam_keys', 'steam-keys', 'steam key', 'steamkey');

update public.products set categoria = 'ia'
  where categoria in ('ia', 'ias', 'inteligencia artificial', 'inteligência artificial');

update public.products set categoria = 'assinaturas'
  where categoria in ('assinatura', 'assinaturas');

update public.products set categoria = 'games'
  where categoria in ('game', 'games');

update public.products set categoria = 'outros'
  where categoria is null or categoria = '';

update public.products
  set ativo = true
  where ativo is null;

update public.products
  set destaque = false
  where destaque is null;

update public.products
  set total_vendas = 0
  where total_vendas is null;

update public.products
  set quantidade = 0
  where quantidade is null;

update public.products
  set created_at = now()
  where created_at is null;

update public.products
  set updated_at = now()
  where updated_at is null;

-- Indexes e constraint de slug/categoria
create unique index if not exists idx_products_slug_unique
  on public.products (slug)
  where slug is not null;

create index if not exists idx_products_total_vendas
  on public.products (total_vendas);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'products_categoria_check'
  ) THEN
    ALTER TABLE public.products
      ADD CONSTRAINT products_categoria_check
      CHECK (categoria in ('games', 'assinaturas', 'steam keys', 'ia', 'outros'));
  END IF;
END $$;

-- Trigger de updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- Funcao para registrar venda (incrementa total_vendas e decrementa quantidade)
create or replace function public.register_product_sale(p_product_id bigint)
returns table(id bigint, total_vendas integer, quantidade integer)
language plpgsql
as $$
begin
  return query
  update public.products
  set total_vendas = coalesce(total_vendas, 0) + 1,
      quantidade = case
        when quantidade is null then null
        else greatest(quantidade - 1, 0)
      end,
      updated_at = now()
  where id = p_product_id
  returning products.id, products.total_vendas, products.quantidade;
end;
$$;

-- Bucket para banners de produtos
insert into storage.buckets (id, name, public)
values ('product-banners', 'product-banners', true)
on conflict (id) do update set public = true;

alter table storage.objects enable row level security;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'objects' AND policyname = 'Public read product banners'
  ) THEN
    CREATE POLICY "Public read product banners"
      ON storage.objects
      FOR SELECT
      USING (bucket_id = 'product-banners');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'objects' AND policyname = 'Admin upload product banners'
  ) THEN
    CREATE POLICY "Admin upload product banners"
      ON storage.objects
      FOR INSERT
      WITH CHECK (
        bucket_id = 'product-banners'
        AND (
          (auth.jwt() -> 'user_metadata' ->> 'role') in ('admin', 'administrador')
          OR (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'administrador')
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'objects' AND policyname = 'Admin update product banners'
  ) THEN
    CREATE POLICY "Admin update product banners"
      ON storage.objects
      FOR UPDATE
      USING (
        bucket_id = 'product-banners'
        AND (
          (auth.jwt() -> 'user_metadata' ->> 'role') in ('admin', 'administrador')
          OR (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'administrador')
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'objects' AND policyname = 'Admin delete product banners'
  ) THEN
    CREATE POLICY "Admin delete product banners"
      ON storage.objects
      FOR DELETE
      USING (
        bucket_id = 'product-banners'
        AND (
          (auth.jwt() -> 'user_metadata' ->> 'role') in ('admin', 'administrador')
          OR (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'administrador')
        )
      );
  END IF;
END $$;

commit;
